"""Added authenticaiton logic

Revision ID: 5328bf578ee0
Revises: 221cfa725960
Create Date: 2023-04-17 11:39:53.039526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5328bf578ee0'
down_revision = '221cfa725960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
