"""Change token name

Revision ID: 5b408d3adb6f
Revises: cd1096c67210
Create Date: 2023-04-18 20:21:21.171211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b408d3adb6f'
down_revision = 'cd1096c67210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.String(), nullable=True))
        batch_op.drop_column('token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('access_token')

    # ### end Alembic commands ###
