"""Spelling Error

Revision ID: 6eb8211e92fd
Revises: 1424a1e2fb01
Create Date: 2023-04-15 18:58:07.044541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb8211e92fd'
down_revision = '1424a1e2fb01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.drop_column('category5')
        batch_op.drop_column('category2')
        batch_op.drop_column('category3')
        batch_op.drop_column('category1')
        batch_op.drop_column('category4')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category4', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('category1', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('category3', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('category2', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('category5', sa.INTEGER(), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
