"""added some bank info

Revision ID: 811c166c7703
Revises: b8f1c28f283e
Create Date: 2023-05-18 21:59:54.647357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811c166c7703'
down_revision = 'b8f1c28f283e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('account_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('account_name')
        batch_op.drop_column('bank_name')

    # ### end Alembic commands ###
