"""Monthly Income

Revision ID: cd1096c67210
Revises: 5328bf578ee0
Create Date: 2023-04-18 15:52:52.681146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1096c67210'
down_revision = '5328bf578ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_total_income', sa.Integer(), nullable=True))
        batch_op.drop_column('annual_total_income')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annual_total_income', sa.INTEGER(), nullable=True))
        batch_op.drop_column('monthly_total_income')

    # ### end Alembic commands ###
